server:
  port: 8102
  servlet:
    context-path: /api/search-server
spring:
  application:
    name: search-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.182.128:3306/intelligent
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.182.128:8848
        namespace: 3df35b9e-228b-42c9-bdf8-fc10c45a0875
    loadbalancer:
      nacos:
        enabled: true
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yaonie.intelligent_assessment_server.search_server.controller
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段
      logic-delete-value: 1
      logic-not-delete-value: 0
logging:
  level:
    com.yaonie.intelligent_assessment_server.search_server.datasource: debug