server:
  frequency: 2  #2秒只能请求一次
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    session:
      cookie:
        path: /
# 线上配置文件
spring:
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 604800
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 驱动类名
    url: jdbc:mysql://${BASE_HOST:127.0.0.1}:3306/intelligent?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
      max-lifetime: 800000
  data:
    redis:
      database: 1
      host: ${BASE_HOST:127.0.0.1}
      port: 6379
      timeout: 5000
#  rabbitmq:
#    host: 192.168.182.128
#    port: 5672
#    username: yaonie
#    password: ${MYSQL_PASSWORD}
#    virtual-host: /
#      password: ${MYSQL_PASSWORD}
#  shardingsphere:
#    mode:
#      type: Standalone
#    #数据源配置
#    datasource:
#      # 多数据源以逗号隔开即可
#      names: intelligent
#      intelligent:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://192.168.182.128:3306/intelligent
#        username: ${MYSQL_USERNAME:root}
#        password: ${MYSQL_PASSWORD}
#    # 规则配置
#    rules:
#      sharding:
#        tables:
#          user_answer:
#            actual-data-nodes: intelligent.user_answer_$->{0..1}
#            # 分表策略
#            table-strategy:
#              standard:
#                sharding-column: appId
#                sharding-algorithm-name: answer-table-inline
#        # 分片算法配置
#        sharding-algorithms:
#          # 自定义分片规则名
#          answer-table-inline:
#            ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
#            type: INLINE
#            props:
#              algorithm-expression: user_answer_$->{appId % 2}
#    props:
#      sql-show: true  # 显示SQL语句，方便调试和验证分表规则是否正确
#    enabled: true
# 对象存储
cos:
  client:
    access-key: ${COS_ACCESSKEY}
    secret-key: ${COS_SECRETKEY}
    region: ap-beijing
    bucket: part-one-1306321377
# AI 配置
ais:
  tag: true
  # 智普 AI
  zhi-pu:
    tag: true
    temperature: 0.95
    apiKey: ${ZHIPU_API_KEY}
# 获取IP地址所属地的工具
area:
  gao-de:
    key: ${GAODE_KEY}
logging:
  level:
    web: debug
#    root: debug
#logging:
#  level:
#    org.springframework.web: INFO
#    com.github.binarywang.demo.wx.mp: DEBUG
#    me.chanjar.weixin: DEBUG
