spring:
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://${BASE_HOST:127.0.0.1}:3306/intelligent?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      max-lifetime: 800000
      maximum-pool-size: 5
  data:
    redis:
      host: ${BASE_HOST:127.0.0.1}
      port: 6379
      timeout: 5000
      database: 8
  #      password: ${MYSQL_PASSWORD}
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: ${BASE_HOST:127.0.0.1}:8848
        namespace: 7daf35b8-6460-4166-a057-e633a0bb1379
    loadbalancer:
      nacos:
        enabled: true
  rabbitmq:
    host: ${BASE_HOST:127.0.0.1}
    port: 5672
    username: yaonie
    password: 351660315Wcl@
    virtual-host: powernode
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
        retry:
          enabled: true
wx:
  mp:
    callback: http://404x395b97.vicp.fun/api
    use-redis: false
    redis-config:
      host: ${BASE_HOST:127.0.0.1}
      port: 6379
      database: 10
    #      password: ${MYSQL_PASSWORD}
    configs: # 多个公众号配置信息
      - appId: wxf161c2344129151f # 第一个公众号的appid
        secret: 5a2f80848317270a542b633bb2f92f98 # 公众号的appSecret
        token: ${WX_TOKEN} # 接口配置里的Token值
    #    callback: ${wx.callback}
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: ${BASE_HOST:127.0.0.1}
        port: 6379
        #        password: ${MYSQL_PASSWORD}
        database: 9
      type: redistemplate